server:
#  servlet:
#    context-path: /v1/
  port: 8080
spring:
  # profiles:
  # active: @spring.profiles.active@
  datasource:
    url: jdbc:postgresql://localhost:5432/cashplus
    username: postgres
    password: 67551951
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

fake-api:
  store:
    url: https://fakestoreapi.com/products

springdoc:
  default-produces-media-type: application/json
